### PR TITLE
[Enhancement] Fixing clean architecture issues

### LINKED ISSUE #3: Fix Clean Architecture issues
Currently the code execution flow violates the `Clean Architecture` principle.
This is because `UIController` invokes and manages the `UI` elements.
However, `Controller` is a layer above the `UI` layer and any layer should not be aware of the layers above it.

Drawback of this approach:
Unit tests for `UIController` cannot be written without creating mocks of `UI` elements.

Resolution:
Code flow should be refactored as following:
- `UI` elements should be created independently in this `UI` package. 
- Upon an user event, the `UIController` should be invoked and relevant user information should be passed.
- `UIController` then generates result (using `Entities` and `Use-cases`) and passes the result back to the invoking `UI` element.
- `UI` element can then render the received result to the user.

### PR DESCRIPTION
**Pull request by pritishmishra**
Description: This PR fixes the clean architecture issues raised by issue: https://github.com/pritishmishra/password_manager/issues/3

Put a tick mark if the PR contains any of the following.
If you plan to address the following in future PRs, leave it unchecked and provide reasons.

- [ ] Unit tests (Report test coverage of the project before and after the PR changes)
- [ ] Exception Handling
- [x] JavaDocs Documentation
- [x] SOLID principles
- [x] Clean Architecture

### CODE REVIEW

File: src/main/controller/UIController.java [hunk 1]
```diff
@@ -0,0 +1,14 @@
+package controller;
+
+import java.awt.event.ActionEvent;
```
Comment (paulgries) [inline src/main/controller/UIController.java]: Ideally, in CA, the controller would probably not have this dependency so that it could be used, for example, with JavaFX or even a web app. But this is good for now!

Comment (pritishmishra) [reply src/main/controller/UIController.java]: Agreed, @paulgries. This got left behind by mistake. I will get rid of it.

File: src/main/UI/StrengthCheckerBox.java [hunk 2]
```diff
@@ -0,0 +1,51 @@
+package UI;
+
+import controller.StrengthCheckerUIControl;
+
+import java.awt.*;
+import java.awt.event.ActionEvent;
+import java.awt.event.ActionListener;
+
+public class StrengthCheckerBox implements ActionListener {
```
Comment (paulgries) [inline src/main/UI/StrengthCheckerBox.java:9]: Instance variable be private, not package-private. Are they accessed from outside this class?

File: src/main/UI/TextField.java [hunk 3]
```diff
@@ -0,0 +1,20 @@
+package UI;
+
+import javax.swing.*;
+
+public class TextField {
+    JTextField textField;
+
+    public TextField() {
+    }
+
```
Comment (paulgries) [inline src/main/UI/TextField.java]: I think this can be package-private rather than public?

File: src/main/UI/StrengthCheckerBox.java [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+        inputLabel.createLabel(70, 60, 260, 30, dialogBox.getJframe(), "Enter your password to check its strength", Color.blue);
+        passwordTextField = new TextField();
+        passwordTextField.createTextField(dialogBox.getJframe(),100,100,200,30);
+        icon = new Icon();
+        icon.createIcon("../resources/icons/password.png");
+        checkPasswordButton = new Button();
+        checkPasswordButton.createButtonWithIcon(dialogBox.getJframe(), "How strong is your password?", icon.getIcon(), 90,150,240,30);
+        checkPasswordButton.getButton().addActionListener(this);
+    }
+
```
Comment (paulgries) [inline src/main/UI/StrengthCheckerBox.java:33]: Is setResult called from outside the class? If not, should it be private?

File: src/main/entities/CustomPassword.java [hunk 5]
```diff
@@ -0,0 +1,16 @@
...
+    public void checkStrength() {
+        strengthChecker.computeStrength(passwordValue);
+    }
+
+    public Strength getStrength() {
+        return strengthChecker.strength;
+    }
+
+    public String getSuggestion() {
+        return strengthChecker.suggestion.getSuggestion();
```
Comment (paulgries) [inline src/main/entities/CustomPassword.java:26]: Should probably use a getter instead of directly accessing .suggestion.

File: src/main/entities/CustomPassword.java [hunk 6]
```diff
@@ -0,0 +1,16 @@
+package entities;
+
+public class CustomPassword extends Password {
+    StrengthChecker strengthChecker = new StrengthChecker();
```
Comment (paulgries) [inline src/main/entities/CustomPassword.java:4]: Should a password be checking its own strength?

File: src/main/entities/PasswordGenerator.java [hunk 7]
```diff
@@ -1,14 +1,15 @@
-package src.passwordgenerator;
+package entities;
 
-import src.UI.DialogBox;
+import UI.DialogBox;
 
 public class PasswordGenerator {
 
     PasswordGenerator() {
+        //TODO: Move this to UIController
```
Comment (paulgries) [inline src/main/entities/PasswordGenerator.java:8]: Just flagging the TODO

File: src/main/entities/PasswordGenerator.java [hunk 8]
```diff
@@ -1,14 +1,15 @@
...
         DialogBox systemDialog = new DialogBox();
     }
     public static void main(String[] args) {
```
Comment (paulgries) [inline src/main/entities/PasswordGenerator.java:11]: Should this main method be removed?

File: src/main/useCases/ComputePasswordStrength.java [hunk 9]
```diff
@@ -0,0 +1,20 @@
+package useCases;
```
Comment (paulgries) [inline src/main/useCases/ComputePasswordStrength.java]: Java naming conventions should be package use_cases

**Review by jcal13 — APPROVED** [review]
Went through with Paul, please address his comments and then merge once resolved.

**Review by paulgries — CHANGES_REQUESTED** [review]
Everything should be as private as possible: private/package-private/protected/public, in that order. IntelliJ flags these, I think.

**Review by paulgries — COMMENTED** [review]
One more thing related to private/public — every public thing should have Javadoc, which is strong incentive to make things as private as possible.

File: src/main/UI/TextField.java (hunk 3 above)
Comment (pritishmishra) [reply src/main/UI/TextField.java]: Yes, I will get rid of constructors that are unused.

File: src/main/entities/PasswordGenerator.java (hunk 7 above)
Comment (pritishmishra) [reply src/main/entities/PasswordGenerator.java:8]: Yeah these would get removed by Rutvik in his PR.

File: src/main/entities/PasswordGenerator.java (hunk 8 above)
Comment (pritishmishra) [reply src/main/entities/PasswordGenerator.java:11]: Yes, this would be removed by Rutvik in his PR.

File: src/main/useCases/ComputePasswordStrength.java (hunk 9 above)
Comment (pritishmishra) [reply src/main/useCases/ComputePasswordStrength.java]: Agreed. Done!

File: src/main/entities/CustomPassword.java (hunk 5 above)
Comment (pritishmishra) [reply src/main/entities/CustomPassword.java:26]: Yeah `suggestion` is just a class variable and we use getter on that.

File: src/main/entities/CustomPassword.java (hunk 6 above)
Comment (pritishmishra) [reply src/main/entities/CustomPassword.java:4]: As per the design, `CustomPassword` has the role of getting a strength for itself and `NewPassword` has the role of getting criteria for itself.

File: src/main/UI/StrengthCheckerBox.java (hunk 4 above)
Comment (pritishmishra) [reply src/main/UI/StrengthCheckerBox.java:33]: Done!

**Comment by pritishmishra** [comment]
> One more thing related to private/public — every public thing should have Javadoc, which is strong incentive to make things as private as possible.

Done!

File: src/classes/Criteria.java [hunk 10]
```diff
@@ -0,0 +1,41 @@
...
+
+        // Check if password contains empty spaces
+        if (password.matches("(\\s)*")) {
+            suggestion.addSuggestion("EMPTY SPACES");
+        }
+        // Check if password has whitespaces
+        else if (password.matches("(.)*(\\s)+(.)*")) {
+            suggestion.addSuggestion("Whitespace not allowed");
+        }
+        // Check if password is greater than 8 chars
```
Comment (paulgries) [inline src/classes/Criteria.java]: Should be greater than or equal to.

File: src/classes/Password.java [hunk 11]
```diff
@@ -0,0 +1,10 @@
+package src.classes;
+
+public abstract class Password {
+
+    /**
+     * Both methods should be over-ridden by child classes.
```
Comment (paulgries) [inline src/classes/Password.java]: Oh! These could be abstract to enforce overriding, no?

**Review by paulgries — APPROVED** [review]
This is looking good enough to ship!
